[package]
authors = ["novacrazy <novacrazy@gmail.com>"]
exclude = ["*.png"]
include = ["Cargo.toml", "src/**/*.rs"]
license = "MIT"
name = "combustion_common"
version = "0.1.0"

[dependencies]
backtrace = "0.3.0"
chrono = "0.2.25"
lazy_static = "0.2.2"
num-traits = "0.1.36"
regex = "0.2"
serde = "0.8.21"
serde_derive = "0.8.21"
slog = "1.4"
slog-atomic = "0.4.3"
slog-scope = "0.2.2"
slog-stream = "1.2.0"
slog-term = "1.3.4"
statrs = "0.4.0"
time = "0.1.35"
vec_map = "0.6.0"
void = "1.0.2"

[dependencies.nalgebra]
path = "../deps/nalgebra"

[dependencies.palette]
git = "git://github.com/Ogeon/palette.git"

[dependencies.tinyfiledialogs]
path = "../deps/tinyfiledialogs"
