[package]
authors = ["Aaron Trent <novacrazy@gmail.com>"]
name = "combustion_macros"
version = "0.1.0"
publish = false

[dependencies]
matches = "0.1"
quote = "0.3"

[dependencies.syn]
features = ["default"]
version = "0.10"

[lib]
proc-macro = true
