[package]
authors = ["Aaron Trent <novacrazy@gmail.com>"]
name = "combustion_macros"
version = "0.1.0"

[dependencies]
matches = "0.1.4"
quote = "0.3.10"

[dependencies.syn]
features = ["default"]
version = "0.10.5"

[lib]
proc-macro = true
