[package]
authors = ["Aaron Trent <novacrazy@gmail.com>"]
name = "combustion_asset"
version = "0.1.0"
publish = false

[dependencies]
capnp = "0.8"
phf = "0.7.20"
phf_macros = "0.7.20"
rayon = "0.6.0"
serde = "0.9"
serde_derive = "0.9"

[dependencies.capnpc]
path = "../deps/capnpc-rust"

[dependencies.assimp]
features = ["default", "compat"]
path = "../deps/assimp-rs"

[dependencies.combustion_common]
path = "../combustion_common"

[dependencies.combustion_protocols]
path = "../combustion_protocols"

[dependencies.lz4]
git = "https://github.com/novacrazy/lz4-rs"

[dependencies.nalgebra]
path = "../deps/nalgebra"
