[package]
authors = ["Aaron Trent <novacrazy@gmail.com>"]
name = "combustion_ecs"
publish = false
version = "0.1.0"

[dependencies]
fnv = "1.0.5"
num_cpus = "1.1.0"
petgraph = "0.4.1"
trace-error = "0.1.4"

[dependencies.specs]
features = ["parallel"]
git = "git://github.com/slide-rs/specs.git"
