[package]
authors = ["Aaron Trent <novacrazy@gmail.com>"]
name = "combustion_window"
version = "0.1.0"

[dependencies]
trace-error = "0.1.4"

[dependencies.glfw]
optional = true
git = "https://github.com/novacrazy/glfw-rs"

[dependencies.glutin]
optional = true
version = "0.7.4"
